spring:
  application:
    name: arq_spring
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_espec
    username: postgres
    password: senh@BD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  flyway:
    url: jdbc:postgresql://localhost:5432/spring_espec
    user: postgres
    password: senh@BD
    baseline-on-migrate: true

#api:
#  security:
#    token:
#      secret: 98b3a9198243172be6a1ecb688567f9905c93250f489c1fa0a4bab507956ebea

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        ruantarcisio: trace
    org:
      springframework:
        web: debug
        security: trace

# trace
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'



springdoc:
  override-with-generic-response: false